spring:
  application:
    name: pong-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:postgresql://localhost:5433/pong_db
    username: postgres
    password: postgres
  data:
    mongodb:
      uri: mongodb://pong:Pong%402026@localhost:27018/pong_db?authSource=admin
  sql:
    init:
      mode: always

server:
  port: 8081
